# Stage 1: Build the application using Gradle
FROM gradle:8.5-jdk17 AS build
WORKDIR /app

# Copy gradle wrapper and source code
COPY build.gradle settings.gradle ./
COPY gradle ./gradle
COPY src ./src

# Build file jar và bỏ qua chạy unit test để nhanh hơn
RUN gradle clean build -x test

# Bước 2: Tạo image chạy (Runtime Image) cực nhẹ
FROM eclipse-temurin:17-jre-alpine
WORKDIR /app

# Copy file jar từ bước build sang image chạy này
# Gradle mặc định build ra file trong thư mục build/libs/
COPY --from=build /app/build/libs/*.jar app.jar

# Chạy ứng dụng
ENTRYPOINT ["java", "-jar", "app.jar"]